openapi: 3.0.0
info:
  version: "1.0.0-oas3"
  title: Reminderly.io UI
  description: This is the reminderly.io UI API
security:
  - accessCode:
      - read
      - write
paths:
  /client:
    get:
      summary: Server example operation
      description: >-
        This is an example operation to show how security is applied to the
        call.
      responses:
        '200':
          description: OK
    delete:
      summary: Server example operation
      description: >-
        This is an example operation to show how security is applied to the
        call.
      responses:
        '200':
          description: OK
  '/client/{id}':
    get:
      summary: Server example operation
      description: >-
        This is an example operation to show how security is applied to the
        call.
      parameters:
        - name: id
          in: path
          description: ID of pet to fetch
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
    put:
      summary: Server example operation
      description: >-
        This is an example operation to show how security is applied to the
        call.
      parameters:
        - name: id
          in: path
          description: ID of pet to fetch
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
    delete:
      summary: Server example operation
      description: >-
        This is an example operation to show how security is applied to the
        call.
      parameters:
        - name: id
          in: path
          description: ID of pet to fetch
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
  /campaign:
    get:
      summary: Server example operation
      description: >-
        This is an example operation to show how security is applied to the
        call.
      responses:
        '200':
          description: OK
    post:
      summary: Server example operation
      description: >-
        This is an example operation to show how security is applied to the
        call.
      responses:
        '200':
          description: OK
  '/campaign/{id}':
    get:
      summary: Server example operation
      description: >-
        This is an example operation to show how security is applied to the
        call.
      parameters:
        - name: id
          in: path
          description: ID of pet to fetch
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
    put:
      summary: Server example operation
      description: >-
        This is an example operation to show how security is applied to the
        call.
      parameters:
        - name: id
          in: path
          description: ID of pet to fetch
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
    delete:
      summary: Server example operation
      description: >-
        This is an example operation to show how security is applied to the
        call.
      parameters:
        - name: id
          in: path
          description: ID of pet to fetch
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
  /packet:
    get:
      summary: Server example operation
      description: >-
        This is an example operation to show how security is applied to the
        call.
      responses:
        '200':
          description: OK
    post:
      summary: Server example operation
      description: >-
        This is an example operation to show how security is applied to the
        call.
      responses:
        '200':
          description: OK
  '/packet/{id}':
    get:
      summary: Server example operation
      description: >-
        This is an example operation to show how security is applied to the
        call.
      parameters:
        - name: id
          in: path
          description: ID of pet to fetch
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
    put:
      summary: Server example operation
      description: >-
        This is an example operation to show how security is applied to the
        call.
      parameters:
        - name: id
          in: path
          description: ID of pet to fetch
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
    delete:
      summary: Server example operation
      description: >-
        This is an example operation to show how security is applied to the
        call.
      parameters:
        - name: id
          in: path
          description: ID of pet to fetch
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
  /purchase:
    get:
      summary: Server example operation
      description: >-
        This is an example operation to show how security is applied to the
        call.
      parameters:
        - name: id
          in: path
          description: ID of pet to fetch
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
    post:
      summary: Server example operation
      description: >-
        This is an example operation to show how security is applied to the
        call.
      parameters:
        - name: id
          in: path
          description: ID of pet to fetch
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
  '/purchase/{id}':
    get:
      summary: Server example operation
      description: >-
        This is an example operation to show how security is applied to the
        call.
      parameters:
        - name: id
          in: path
          description: ID of pet to fetch
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
  /credits:
    get:
      summary: Server example operation
      description: >-
        This is an example operation to show how security is applied to the
        call.
      responses:
        '200':
          description: OK
  /dashboard:
    get:
      summary: Server example operation
      description: >-
        This is an example operation to show how security is applied to the
        call.
      responses:
        '200':
          description: OK
  '/report/{name}':
    get:
      summary: Server example operation
      description: >-
        This is an example operation to show how security is applied to the
        call.
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
  /ping:
    get:
      summary: Server heartbeat operation
      description: >-
        This operation shows how to override the global security defined above,
        as we want to open it up for all users.
      security: []
      responses:
        '200':
          description: OK
servers:
  - url: 'https://virtserver.swaggerhub.com/reminderly/reminderly-ui/v1'
components:
  securitySchemes:
    accessCode:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'http://reminderly.io/oauth/auth'
          tokenUrl: 'http://reminderly.io/oauth/token'
          scopes:
            write: allows modifying resources
            read: allows reading resources